/**
 * 统一错误码枚举（CONTRIBUTING.md §3 API 命名）。
 * 后续 API 错误响应均带 error_code 字段。
 */
export const ERROR_CODES = {
  // 认证 / 授权
  ERR_AUTH_REQUIRED: 'ERR_AUTH_REQUIRED',
  ERR_AUTH_INVALID_CREDENTIALS: 'ERR_AUTH_INVALID_CREDENTIALS',
  ERR_AUTH_TOTP_REQUIRED: 'ERR_AUTH_TOTP_REQUIRED',
  ERR_AUTH_TOTP_INVALID: 'ERR_AUTH_TOTP_INVALID',
  ERR_AUTH_RATE_LIMITED: 'ERR_AUTH_RATE_LIMITED',

  // 资源
  ERR_ITEM_NOT_FOUND: 'ERR_ITEM_NOT_FOUND',
  ERR_SNAPSHOT_NOT_FOUND: 'ERR_SNAPSHOT_NOT_FOUND',
  ERR_COLLECTION_NOT_FOUND: 'ERR_COLLECTION_NOT_FOUND',

  // 输入校验
  ERR_INVALID_URL: 'ERR_INVALID_URL',
  ERR_VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',

  // 采集 / Worker
  ERR_CAPTURE_TIMEOUT: 'ERR_CAPTURE_TIMEOUT',
  ERR_CAPTURE_FAILED: 'ERR_CAPTURE_FAILED',
  ERR_LOGIN_WALL: 'ERR_LOGIN_WALL',
  ERR_DRM_BLOCKED: 'ERR_DRM_BLOCKED',

  // 内部
  ERR_INTERNAL: 'ERR_INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
